** Usage

Put: 

#+BEFIN_SRC lisp
(load-module "ratcontrol")
(ratcontrol-initialize your-monitor's-x-resolution your-monitor's-y-resolution)
#+END_SRC

in your =~/.stumpwmrc= (or your =~/.stumpwm.d/init.lisp=), and the module will 
be ready for use. 

*** Dependencies:
    Ratcontrol depends upon XTest, CLX, and XTE. Without xtest and clx, ratcontrol
    wont work. Without xte, scrolling wont work (C-M-c and C-M-C).
** Example

Run =colon=, type =ratcontrol-binary=, and ratcontrol will be activated. 
Optionally you can type =ratcontrol-help= to bring up the keybinding list. 

** Readme: 

this module is for controlling the pointer with the keyboard.
it defines an interactive keymap that cuts the 'click area' in half 
with every movement of the pointer. in this way we optimally get O(log(n))
efficiency when moving the pointer. it should take an average of 9 cuts to click
if its a small button. if its a large text field it will average 3-4 cuts. 

** TODO:

-Refactor =ratcontrol-help= to be dynamically generated by the =ratcontrol= 
 keymap. 
-create command to cycle snaps, ie snap to the edge of the clickable area. 
-create command for ratcontrol on only a specific frame. ie start ratcontrol
 with a specific offset, and warp from there. this requires grabbing the frames 
 dimensions and position. 
